var Countries = ["London", "Greece", "Switzerland", "Korea", "Turkey"];
console.log(Countries);
Countries.sort();
console.log(Countries.sort());
Countries.sort().reverse();
console.log(Countries.sort().reverse());
console.log(Countries);
Countries.reverse();
console.log(Countries);
Countries.reverse();
console.log(Countries.reverse());
Countries.sort();
console.log(Countries.sort());
Countries.sort().reverse();
console.log(Countries.sort().reverse());
