var car1 = 'subaru';
console.log("Is car1 == 'subaru'? I predict True.");
console.log(car1 == 'subaru');
console.log("Is car1 == 'toyota'? I predict False.");
console.log(car1 == 'toyota');
var car2 = 'audi';
console.log("Is car2 == 'audi'? I predict True.");
console.log(car2 == 'audi');
console.log("Is car2 == 'honda'? I predict False.");
console.log(car2 == 'honda');
var car3 = 'suzuki';
console.log("Is car3 == 'suzuki'? I predict True.");
console.log(car3 == 'suzuki');
console.log("Is car3 == 'subaru'? I predict False.");
console.log(car3 == 'subaru');
var car4 = 'toyota';
console.log("Is car4 == 'toyota'? I predict True.");
console.log(car4 == 'toyota');
console.log("Is car4 == 'audi'? I predict False.");
console.log(car4 == 'audi');
var car5 = 'mehran';
console.log("Is car5 == 'mehran'? I predict True.");
console.log(car5 == 'mehran');
console.log("Is car5 == 'toyota'? I predict False.");
console.log(car5 == 'toyota');
var car6 = 'land cruiser';
console.log("Is car6 == 'land cruiser'? I predict True.");
console.log(car6 == 'land cruiser');
console.log("Is car6 == 'mehran'? I predict False.");
console.log(car6 == 'mehran');
var car7 = "corolla";
console.log("Is car7 == 'corolla'? I predict True.");
console.log(car7 == 'corolla');
console.log("Is car7 == 'suzuki'? I predict False.");
console.log(car7 == 'suzuki');
var car8 = 'ford';
console.log("Is car8 == 'ford'? I predict True.");
console.log(car8 == 'ford');
console.log("Is car8 == 'corolla'? I predict False.");
console.log(car8 == 'corolla');
var car9 = 'BMW';
console.log("Is car9 == 'BMW'? I predict True.");
console.log(car9 == 'BMW');
console.log("Is car9 == 'ford'? I predict False.");
console.log(car9 == 'ford');
var car10 = 'chervolet';
console.log("Is car10 == 'chervolet'? I predict True.");
console.log(car10 == 'chervolet');
console.log("Is car10 == 'BMW'? I predict False.");
console.log(car10 == 'BMW');
